### ISSUE TITLE
Missing dependency `matrix` for ruby versions >= 3.1.0

### ISSUE THREAD

**Issue by jenskdsgn** [daugaard/linear-regression#4]
As of Ruby 3.1.0, matrix is not bundled with Ruby anymore and should be part of the dependency list.

https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

<img width="606" alt="image" src="https://github.com/user-attachments/assets/5a736e2f-3a39-4d3f-a8cf-3d3c05c9c33f">

Can you please add this to your Gemspec?

**Comment by sorendaugaard** [comment]
Thank you so much for reporting this.

This has been addressed in the latest version.

**Comment by daugaard** [comment]
Thank you so much for reporting this.

This has been addressed in the latest version.
